resources:
  - name: git
    type: git
    source:
      uri: git@github.com:MERN-Stack-Dev-Group-graphQL/neighborly-client.git
      branch: master
      private_key: ((private_key))
#   - name: s3-ui-deploy
#     type: s3
#     source:
#       bucket: app.neighborly.tools      
#       access_key_id: ((AWS_ACCESS_KEY_ID))
#       secret_access_key: ((AWS_SECRET_ACCESS_KEY))
  - name: s3-ui-build
    type: s3
    source:
      bucket: neighborly.tools.build      
      versioned_file: neighborly-client.tar.gz
      access_key_id: ((AWS_ACCESS_KEY_ID))
      secret_access_key: ((AWS_SECRET_ACCESS_KEY))
jobs:
  - name: neighborly-client-dev
    plan:
      - get: git
        trigger: true      
      - task: build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: node
              username: ((DOCKER_USER))
              password: ((DOCKER_PASS))
              tag: 14.15.1-alpine3.11
          inputs:
            - name: git
          outputs:
            - name: client
              path: git
          params:
            NEIGHBORLY_ENV: ((neighborly_env))
          run:
            path: /bin/sh
            args:
              - -xc
              - |
                ls -a
                which node
                node -v
                cd git                               
                npm i &&
                echo "$NEIGHBORLY_ENV" >> .env
                npm i react-scripts@3.4.1 -g                
                npm install node-sass -g
                ls -a
                npm run-script build
                pwd
                ls -a
                tar -zcvf neighborly-client.tar.gz -C build . 
                ls                               
      - put: s3-ui-build
        params:
          file: client/neighborly-client.tar.gz
      - task: deploy
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ubuntu
          inputs:
            - name: s3-ui-build
              path: .
          params:
            unpack: true
            ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
            SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))                   
          run:
            path: /bin/sh
            args:
              - -xc
              - |
                apt-get update &&
                DEBIAN_FRONTEND=noninteractive apt-get -y install awscli
                export AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID ; export AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY
                mkdir client && tar -xvf neighborly-client.tar.gz -C client .
                ls -la
                aws s3 ls                
                aws s3 sync ./client s3://dev.neighborly.tools      
  - name: neighborly-client-staging
    plan:
      - get: s3-ui-build        
        passed: [neighborly-client-dev]      
      - task: deploy
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ubuntu
          inputs:
            - name: s3-ui-build
              path: .
          params:
            unpack: true
            ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
            SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))         
          run:
            path: /bin/sh
            args:
              - -xc
              - |
                apt-get update &&
                DEBIAN_FRONTEND=noninteractive apt-get -y install awscli
                export AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID ; export AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY
                mkdir client
                pwd
                ls -la
                tar -xvf neighborly-client.tar.gz -C client .
                ls -la client
                aws s3 ls                
                aws s3 sync client s3://staging.neighborly.tools
  - name: neighborly-client-prod
    plan:
      - get: s3-ui-build        
        passed: [neighborly-client-staging]      
      - task: deploy
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ubuntu
          inputs:
            - name: s3-ui-build
              path: .
          params:
            unpack: true
            ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
            SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))         
          run:
            path: /bin/sh
            args:
              - -xc
              - |
                apt-get update &&
                DEBIAN_FRONTEND=noninteractive apt-get -y install awscli
                export AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID ; export AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY
                mkdir client
                pwd
                ls -la
                tar -xvf neighborly-client.tar.gz -C client .
                ls -la client
                aws s3 ls                
                aws s3 sync client s3://app.neighborly.tools
